#ifndef __AMR__
#define __AMR__
#define AMR_DECODED_FRAME_SIZE 320
#define AMRNB_FORMAT_FREQUENCY 		8000
#define AMRWB_FORMAT_FREQUENCY 		16000
#define AMR_FORMAT_BITS_PER_SAMPLE 	16
#define AMR_FORMAT_CHANNEL_COUNT 	1
#define OK 0
#define INVALID_ARGUMENT -1
#define INVALID_FORMAT -2
#define INITIALIZATION_ERROR -3
#endif