/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_maximgorin_media_amr_NbEncoder_Mode */

#ifndef _Included_ru_maximgorin_media_amr_NbEncoder_Mode
#define _Included_ru_maximgorin_media_amr_NbEncoder_Mode
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
